--
-- mod-azor-api: account ↔ external identity links (Stage 5).
--
-- Two tables. `mod_azor_api_pending_links` holds short-lived codes a client
-- registers via `.azor api link begin`; the player redeems one in-game via
-- `.azor api link confirm <code>`, which moves the (source, external_id) into
-- the authoritative `mod_azor_api_account_links` table keyed on the redeeming
-- player's account_id.
--
-- Why split pending vs confirmed:
--   • Confirmed rows are PK'd on (external_source, external_id) — one external
--     identity maps to one game account, period. Mixing pending + confirmed
--     into one table would force a wider PK (or a nullable account_id) and
--     would obscure the "is this link active?" query.
--   • The pending row never carries an account_id — the whole point is that
--     the game account is only known once the player runs the in-game confirm.
--
-- No FK to `account.id` — see the `azerothcore-module-character-persistence`
-- skill. Cleanup is handled by `AzorApiAccountScript::OnAccountLogin/Delete`
-- in C++. Pending rows are reaped lazily on every `link begin` call (no
-- background worker required).
--

CREATE TABLE IF NOT EXISTS `mod_azor_api_pending_links` (
    `code`            CHAR(8)                          NOT NULL COMMENT 'opaque single-use claim code, generated by the requesting client',
    `external_source` ENUM('discord','website')        NOT NULL,
    `external_id`     VARCHAR(64)                      NOT NULL COMMENT 'discord user id, website session, ...',
    `created_at`      BIGINT UNSIGNED                  NOT NULL COMMENT 'epoch ms',
    `expires_at`      BIGINT UNSIGNED                  NOT NULL COMMENT 'epoch ms; lazy-reaped on next link begin',
    PRIMARY KEY (`code`),
    KEY `idx_external` (`external_source`, `external_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `mod_azor_api_account_links` (
    `account_id`      INT(10) UNSIGNED                 NOT NULL COMMENT 'account.id (auth)',
    `external_source` ENUM('discord','website')        NOT NULL,
    `external_id`     VARCHAR(64)                      NOT NULL,
    `linked_at`       BIGINT UNSIGNED                  NOT NULL COMMENT 'epoch ms',
    PRIMARY KEY (`external_source`, `external_id`),
    KEY `idx_account` (`account_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
